/**
 * Daybook — Express entry point
 *
 * Runs in its own container (port 8090). Apache proxies daybook.torama.money
 * to it. Serves the PWA frontend + REST API from one process.
 */
'use strict';

const path = require('path');
const express = require('express');

function mustEnv(name, hint) {
  if (!process.env[name]) { console.error(`[FATAL] missing env ${name} — ${hint}`); process.exit(1); }
}
mustEnv('JWT_SECRET', 'HS256 session signing key. Generate: openssl rand -hex 32');
mustEnv('DATABASE_URL', 'Postgres connection string. e.g. postgres://user:pass@host:5432/daybook');
if (!process.env.GOOGLE_CLIENT_ID) console.warn('[WARN] GOOGLE_CLIENT_ID not set — Google sign-in will be disabled until it is configured.');

const { initDb } = require('./db');
const { ensureSeed } = require('./seed');

const PORT = process.env.PORT || 8090;
const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1);

// tiny cookie parser (only needs daybook_token; express.res.cookie/clearCookie are built in)
app.use((req, _res, next) => {
  req.cookies = {};
  const c = req.headers.cookie;
  if (c) for (const part of c.split(';')) { const i = part.indexOf('='); if (i > 0) req.cookies[part.slice(0, i).trim()] = decodeURIComponent(part.slice(i + 1).trim()); }
  next();
});

// keep the raw body so payment webhooks can verify their HMAC signatures; the
// larger limit accommodates attendance photo + signature captures (base64).
app.use(express.json({ limit: '6mb', verify: (req, _res, buf) => { req.rawBody = buf; } }));

// security headers
app.use((_req, res, next) => {
  res.set('X-Frame-Options', 'SAMEORIGIN');
  res.set('X-Content-Type-Options', 'nosniff');
  res.set('Referrer-Policy', 'strict-origin-when-cross-origin');
  next();
});

app.get('/healthz', (_req, res) => res.json({ status: 'ok', service: 'daybook' }));

// ── static PWA frontend (Vite-built React) ────────────────────────────────
// Build output lives in frontend/dist/ (generated by `npm run build` / Dockerfile).
const FRONTEND = path.join(__dirname, '../frontend/dist');
// The service worker must always be revalidated so updates are detected
// immediately (no stale worker held for up to an hour in the HTTP cache).
app.get('/sw.js', (_req, res) => {
  res.set('Cache-Control', 'no-cache, no-store, must-revalidate');
  res.type('application/javascript').sendFile(path.join(FRONTEND, 'sw.js'));
});
app.use(express.static(FRONTEND, { maxAge: '1h', index: false }));
// SPA fallback — everything not under /api and not a static asset → index.html.
// index.html is no-cache so it always loads the current shell + service worker.
app.get('*', (req, res, next) => {
  if (req.path.startsWith('/api')) return next();
  res.set('Cache-Control', 'no-cache');
  res.sendFile(path.join(FRONTEND, 'index.html'));
});

// multer + generic error handler
app.use((err, _req, res, _next) => {
  if (err) {
    const code = err.code === 'LIMIT_FILE_SIZE' ? 413 : 400;
    return res.status(code).json({ error: err.message || 'request error' });
  }
});

// ── async startup ─────────────────────────────────────────────────────────────
(async () => {
  try {
    await initDb();           // connect pool + run migrations
    await ensureSeed();       // first-boot: superadmins + Fido/Fiafia tenants & sites

    // routes require db to be ready — register after initDb
    const api = require('./routes');
    app.use('/api', api);

    // HTTP server + WebSocket realtime gateway (live sales / gate / loading).
    const http = require('http');
    const server = http.createServer(app);
    try { require('./realtime').attach(server); } catch (e) { console.error('[rt] gateway not attached:', e.message); }

    server.listen(PORT, () => {
      console.log(`[Daybook] listening on :${PORT} (${process.env.NODE_ENV || 'development'})`);
      try { require('./scheduler').start(); } catch (e) { console.error('[sync] scheduler not started:', e.message); }
      try { require('./livefeed').start(); } catch (e) { console.error('[livefeed] not started:', e.message); }
      try { require('./mailer').startOutboxWorker(); } catch (e) { console.error('[mailer] outbox worker not started:', e.message); }
    });
  } catch (e) {
    console.error('[FATAL] startup failed:', e.message);
    process.exit(1);
  }
})();
